name: Package Dev Layer4
on: 
  workflow_dispatch:
  push:
    tags:
      - "*w*"
      
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: 加载版本号
      run: echo "VERSION=$(cat DEV-VERSION)" >> $GITHUB_ENV  

    - name: 安装依赖
      run: |
        sudo apt update
        sudo apt install curl wget tar unzip zstd -y
    - name: 拉取文件
      run: |
        sudo wget -O caddyd.tar.gz https://github.com/WJQSERVER/caddy/releases/download/${{ env.VERSION }}/caddy-linux-amd64-l4.tar.gz
        sudo tar -xzvf caddyd.tar.gz
        sudo mkdir -p caddy_web
        sudo mv caddy caddy_web/

    - name: Package /pages directory
      run: | 
        sudo cp -r pages caddy_web/
        sudo tar -czf caddy-linux-amd64-pages-l4.tar.gz -C caddy_web .
        sudo tar -I zstd -cf caddy-linux-amd64-pages-l4.tar.zst -C caddy_web .

    - name: 上传Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.VERSION }}
        artifacts: ./caddy-linux-amd64-pages-l4.tar.zst, ./caddy-linux-amd64-pages-l4.tar.zst
        token: ${{ secrets.REPO_TOKEN }}
        tag: ${{ env.VERSION }}
        allowUpdates: true
        prerelease: true
      env:
        export PATH: $PATH:/usr/local/go/bin
