name: XCaddy Daily
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # 每天3点执行
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
          
    steps:
      - name: 导入仓库内容
        uses: actions/checkout@v3

      - name: 加载时间戳版本号
        run: |
          echo "VERSION=$(date +%Y%m%d)" >> $GITHUB_ENV 
          echo "${{ env.VERSION }}" 

      - name: APT安装依赖
        run: |
          sudo apt update
          sudo apt install curl vim wget gnupg dpkg apt-transport-https lsb-release ca-certificates tar zstd -y

      - name: 部署Go环境
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.1

      - name: 部署Xcaddy
        run: |
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-xcaddy-archive-keyring.gpg
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-xcaddy.list
          sudo apt update
          sudo apt install -y xcaddy
          
      - name: 打包编译-EXTRA
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          xcaddy build --with github.com/caddyserver/cache-handler --with github.com/ueffel/caddy-brotli --with github.com/caddyserver/transform-encoder --with github.com/RussellLuo/caddy-ext/ratelimit --with github.com/caddy-dns/cloudflare
          tar -czvf caddy-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz caddy
          tar -I 'zstd -15' -cf caddy-${{ matrix.goos }}-${{ matrix.goarch }}.tar.zst caddy
            
      - name: 打包编译-L4
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          xcaddy build --with github.com/caddyserver/cache-handler --with github.com/ueffel/caddy-brotli --with github.com/caddyserver/transform-encoder --with github.com/RussellLuo/caddy-ext/ratelimit --with github.com/caddy-dns/cloudflare --with github.com/mholt/caddy-l4
          tar -czvf caddy-${{ matrix.goos }}-${{ matrix.goarch }}-l4.tar.gz caddy
          tar -I 'zstd -15' -cf caddy-${{ matrix.goos }}-${{ matrix.goarch }}-l4.tar.zst caddy
    
      - name: 打包编译-PURE
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          xcaddy build
          tar -czvf caddy-${{ matrix.goos }}-${{ matrix.goarch }}-pure.tar.gz caddy
          tar -I 'zstd -15' -cf caddy-${{ matrix.goos }}-${{ matrix.goarch }}-pure.tar.zst caddy  

      - name: 上传至Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: Daily Build
          artifacts: ./caddy*.tar.gz, ./caddy*.tar.zst
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: daily
          body: Daily Build - Caddy ${{ env.VERSION }}
          allowUpdates: true
          prerelease: true
        env:
          export PATH: $PATH:/usr/local/go/bin
